This is makeindex, version 2.15 [TeX Live 2009] (kpathsea + Thai support).
Scanning style file ./rgbulb.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file rgbulb.acn....done (54 entries accepted, 0 rejected).
Sorting entries....done (350 comparisons).
Generating output file rgbulb.acr....done (37 lines written, 0 warnings).
Output written in rgbulb.acr.
Transcript written in rgbulb.alg.
